apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
    tier: app

spec:
  replicas: 3
  selector:
    matchLabels:      
      app: worker
      tier: app
    
  template:
    metadata:
      labels:        
        app: worker
        tier: app
    spec:
      containers:
        - name: worker-container
          image: reidn3r/ml-inference-worker:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: worker-environment
          resources: #min. garantido
            requests:
              cpu: "0.2"    
              memory: "300Mi" 

            limits: #max. permitido
              cpu: "1"    
              memory: "1Gi" 
          ports:
            - containerPort: 3031
